### ISSUE TITLE
error result attribute didn't work for me in useReadCypher

### ISSUE THREAD

**Issue by jexp** [adam-cowley/use-neo4j#5]
even when I passed an invalid cypher query it didn't return an error (message)

**Comment by adam-cowley** [comment]
I've added some tests in https://github.com/adam-cowley/use-neo4j/commit/feef55d86843e9d079ccf542516034d0af54e3c4 which verify the fixes for this issue - version 0.2.20 published to npm

**Comment by adam-cowley** [comment]
Fixed in https://github.com/adam-cowley/use-neo4j/commit/1d4c751f609cb1125f17d0925adf462344fdcfb8 - the error is no longer re-thrown
